### ISSUE TITLE
astrokep.filter_kepler_lcdict

### ISSUE THREAD

**Issue by lgbouma** [waqasbhatti/astrobase#16]
An issue with the current (commented out) approach is that SAP and PDC fluxes have nans at different positions. 

The typical use-case is "I want SAP fluxes" or "I want PDC fluxes". I think it might be more sensible to have this function reorganize the lcdict, perhaps bookkeeping the same things as currently tracked in lcdict['columns'], but with two separate sub-dicts: one for PDC, one for SAP.

**Comment by waqasbhatti** [comment]
I forget if the pdcsap_flux and sap_flux have the same lengths (this was written a while ago). If so, that procedure seems OK.

Might want to do:
```
LCDATAKEYS = same but remove PDCSAP_FLUX, PDCSAP_FLUX_ERR, SAP_FLUX, 
SAP_FLUX_ERR, SAP_BKG, SAP_BKG_ERR
```
Add instead:
```
BKGDATAKEYS = ['SAP_BKG','SAP_BKG_ERR']
SAPDATAKEYS = ['SAP_FLUX','SAP_FLUX_ERR']
PDCDATAKEYS = ['PDCSAP_FLUX','PDC_SAPFLUX_ERR']
```
And appropriate kwargs to the initial read_kepler_fitslc function. Then add to the lcdict initial definition:
```
'bkg':{},
'sap':{},
'pdc':{},
```
Then instead of:
```
for key in datakeys:
        lcdict[key.lower()] = lcdata[key]
```
Do:
```
for key in bkgdatakeys:
    lcdict['bkg'][key.lower()] = lcdata[key]
for key in sapdatakeys:
    blah
for key in pdcdatakeys:
    blah
```
Will have to change the filter_kepler_lcdict function appropriately.

I'll can probably do all of this later tonight if you don't get to it first.

**Comment by lgbouma** [comment]
I wound up doing it in a fast way in something that I wasn't planning to commit because I wanted to be testing a detrending module -- so all clear from my end!

**Comment by waqasbhatti** [comment]
Should be fixed in the latest commit.
