### ISSUE TITLE
sigma clipping whole lc vs. bins

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#26]
Using prewhiten_magseries() on some RR Lyrae light curves, I found that the call to sigclip_magseries() with the default setting (sigclip=3.0) was removing some of the of the lc points at the peak.  See attached image.  I can and will set sigclip to be a larger value than 3.0 to avoid this, but it may be worth considering different versions of sigma clipping (sigma clipping in bins, for example, though the steep rise of RR Lyrae stars may break that as well.)

![temp](https://user-images.githubusercontent.com/5067798/32023272-b675f490-b9a6-11e7-9f7f-1ac9e991670c.png)

**Comment by waqasbhatti** [comment]
Adding different sigclips for binned vs unbinned LCs is a bit complicated, so I think I won't do that for now. But what I actually do need to do is add iterative sigma-clipping, so it doesn't blindly chop things off if they're over the limit. This will be added soonish.

For now, note that you can also set it up so there's asymmetric sigma-clipping (e.g. more on the low side and less on the high side) by using a list as the sigclip kwarg:

```
sigclip=[lo,hi]
```

**Comment by waqasbhatti** [comment]
Added an iterative version of sigclip_magseries in v0.2.7. Would be good to test it some more; it appears to be working as expected. It may be too aggressive though, since it uses medians and 1.483 x MADs instead of means and stdevs. I'll probably switch over to stdevs because that's probably more expected behavior, but keep the medians for central value estimates.
