### ISSUE TITLE
sigclip_magseries assumes inputs are np.array()'s

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#33]
sigclip_magseries assumes that the times, mags, and errs inputs are np.array()'s right from the beginning with the ``ftimes, fmags, ferrs = times[find], mags[find], errs[find]`` syntax.  Maybe it should be checked that these actually are np.array()'s?  I'm not sure what the implications are for the rest of astrobase in providing for non-numpy-arrays to be possible inputs.

**Comment by waqasbhatti** [comment]
I think this is probably a difficult thing to not require for astrobase functions. I guess I could do stuff like `np.as1d()` or something right off the bat in every function, but a bit too much for not enough gain IMO.

If there's an error or something that caused:
```python
ftimes, fmags, ferrs = times[find], mags[find], errs[find]
```
to fail, what was the input used? If it was lists, then if you wrap them with `np.as1d()` or `np.array()`, should work fine. If it was an astropy.Table column, then that's probably something I should look at because that's supposed to be a np.array in disguise and should work transparently.

**Comment by joshuawallace** [comment]
They were lists.  I've converted them to numpy arrays now simple enough, it just took me some work to realize what the cause of the error was.

**Comment by waqasbhatti** [comment]
Ah OK. Everything turned out to work correctly, I hope.

 I'll go ahead and close this. Can re-open if other astrobase input weirdness pops up.
