### ISSUE TITLE
checkplot_pickle() not ignoring non-existence information in objectinfo dict

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#36]
In using checkplot_pickle(), I have created an objectinfo dict that contains only objectid, ra, and decl as elements.  However, checkplot_pickle() at this point starts looking for magnitudes in objectinfo and fails because it can't find any magnitude information.  The specific error message I am getting:

> gaiak_colors = gaia_mags - objectinfo['kmag']
> KeyError: 'kmag'

If I do not pass an objectinfo dict in to checkplot_pickle(), I do not get this error and the function runs successfully.  It's only when I pass in an objectinfo dict that it starts wanting more than I'm giving it.

**Comment by waqasbhatti** [comment]
Thanks for noticing this! Definitely a bug.

This is now fixed in f0143ccd3312f4a946cc84101f661bc3b49abec1. 

b0ac3d3f8ece64d43a0faeeda5f7bb7d855aa115 has additional fixes for handling missing info in the checkplotserver webapp interface.

I'll roll a new release of astrobase later this week when I fix #34, but for now (and maybe later for immediate fixes to bugs you find) it might be best to use the github version of astrobase. To do this:

- git clone this repository somewhere: `git clone https://github.com/waqasbhatti/astrobase`
- with your virtualenv activated, cd into the cloned directory, and then: `pip install -e .`
- this will use the git cloned version of astrobase, which you can always keep up to date by doing a `git pull origin master`

**Comment by waqasbhatti** [comment]
This is now also available in v0.3.8.
