### ISSUE TITLE
Finder plot cross hair off

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#48]
The cross hair in the finder plot looks like it's off slightly.  The horizontal line definitely is a bit low, by perhaps a pixel or two.  The vertical line seems right.

**Comment by waqasbhatti** [comment]
Can you attach the PNG? I tried to fix this a couple of weeks ago, but I guess it's still not working correctly.

**Comment by joshuawallace** [comment]
![checkplot-6045479314548709376_3](https://user-images.githubusercontent.com/5067798/38705751-a4bbfb08-3e78-11e8-8850-71f65fec1096.png)

**Comment by joshuawallace** [comment]
![checkplot-6045479829935383680_5](https://user-images.githubusercontent.com/5067798/38706080-dfdb37a2-3e79-11e8-8fcb-b83d4db819ee.png)

**Comment by waqasbhatti** [comment]
Thanks! That looks like the finder chart from before my fixes in 9c901b810bb49eb49d53d1ae03c5ca7dd5a4d93f. Can you try regenerating this checkplot with the latest github version? Or, using the objectinfo dict from your light curve, run something like:

```python
cpd = checkplot._pkl_finder_objectinfo(your_lc_objectinfo, 
                                       None, 'gray_r', None, 
                                       None, 'globalmedian', 4.0)
checkplot._base64_to_file(cpd['finderchart'],'finderchart-test.png')
```
to regenerate just the finder chart with the new code. Then see if finderchart-test.png looks as expected.

**Comment by waqasbhatti** [comment]
I changed this a bit to make the cross hairs fall on the actual pixel coordinates of the object using the WCS from the DSS FITS instead of just the center of the FITS previously. Should hopefully be more consistent now.

**Comment by joshuawallace** [comment]
Yes, I am using an old version of checkplot.py, which I have adapted for including the red model fit and the text.

Here is the plot I get using the code from commit 3497992 (Thu Apr 12 08:44:23 2018 -0400):
![temp](https://user-images.githubusercontent.com/5067798/38743025-0e0c98d6-3f0c-11e8-8de7-c142c6b6d48c.png)


And here is the plot I get using the most recent commit, d3c6dea

![temp2](https://user-images.githubusercontent.com/5067798/38743111-3aaa2c1e-3f0c-11e8-963f-06b41e787d77.png)

It appears in the most recent commit that both of the crosshairs are off.

**Comment by waqasbhatti** [comment]
OK, I think I'll stick with the (RA, Dec) -> (x,y) for the cross-hair coordinates because I think that's the right way to do this. I'm not sure how matplotlib figures out the baseline for a `linewidth=2.0` line, i.e. I'm not sure if it makes it so the line center is the desired coordinate in `plt.axvline` or `plt.axhline`, so I'll make `linewidth=1.0` for now. 

![checkplot-hat-314-0000816 1](https://user-images.githubusercontent.com/1868184/38744641-573c6fe6-3f10-11e8-8cb2-c7d1744b2140.png)

The other issue is that the DSS finder images are at least a decade old, so if the objects are moving (and we use J2000 coordinates), the (x,y) is likely to be a bit off. I could maybe fix this by precessing the J2000 coordinates back to the epoch of the finder image and using those to get the precise (x,y), but I think that's overkill for now. I may do this later though.
